apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-users-provisioning
  namespace: {{ include "grafana.namespace" . }}
  labels:
    app: grafana
data:
  users.yaml: |
    {{- range .Values.grafana.provisioning.users }}
    - name: {{ .name }}
      email: {{ .email }}
      password: {{ .password }}
      role: {{ .role }}
    {{- end }}